# Generated by Django 3.1.5 on 2021-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Qty',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_sum',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Sum'),
        ),
    ]
