# Generated by Django 3.1.5 on 2021-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Product_name')),
                ('Price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('Qty', models.DecimalField(decimal_places=0, max_digits=4)),
                ('num_sum', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
    ]
